config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :evaluations
  resources :tasks
  resources :scenarios

  # Set evaluation sequence
  resources :scenarios do
    member do
      get 'start'
      get 'evaluations'
    end
    resources :tasks, only: %i[show] do
      member do
        get 'next'
      end
      resources :gpt_prompts, only: %i[create]
      resources :evaluations, only: %i[new create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "scenarios#index"
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :task
  belongs_to :user

  validates :accuracy, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :accuracy_description, presence: true, length: { minimum: 15, maximum: 120 }
  validates :relevance, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :relevance_description, presence: true, length: { minimum: 15, maximum: 120 }
  validates :bias, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :bias_description, presence: true, length: { minimum: 15, maximum: 120 }
  validates :comments, length: { maximum: 500 }
  validates :task_id, presence: true
  validates :user_id, presence: true
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: %i[ show edit update destroy ]
  before_action :set_task, only: %i[ new create ]
  before_action :set_scenario, only: %i[ new create ]
  before_action :authenticate_user!

  # GET /evaluations or /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1 or /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations or /evaluations.json
  def create
    @evaluation = @task.evaluations.new(evaluation_params)
    @evaluation.task = @task
    @evaluation.user = current_user

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to next_scenario_task_path(@task.scenario, @task), notice: 'Evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1 or /evaluations/1.json
  def update
    @tasks = Task.all
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to evaluation_url(@evaluation), notice: "Evaluation was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1 or /evaluations/1.json
  def destroy
    @evaluation.destroy!

    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: "Evaluation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    def set_task
      @task = Task.find(params[:task_id])
      puts @task
    end

    def set_scenario
      @scenario = Scenario.find(params[:scenario_id])
    end

    # Only allow a list of trusted parameters through.
    def evaluation_params
      params.require(:evaluation).permit(:accuracy, :accuracy_description, :relevance, :relevance_description, :bias, :bias_description, :comments, :task_id)
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_evaluation.html.erb
<div id="<%= dom_id evaluation %>">
  <p>
    <strong>Accuracy:</strong>
    <%= evaluation.accuracy %>
  </p>

  <p>
    <strong>Accuracy description:</strong>
    <%= evaluation.accuracy_description %>
  </p>

  <p>
    <strong>Relevance:</strong>
    <%= evaluation.relevance %>
  </p>

  <p>
    <strong>Relevance description:</strong>
    <%= evaluation.relevance_description %>
  </p>

  <p>
    <strong>Bias:</strong>
    <%= evaluation.bias %>
  </p>

  <p>
    <strong>Bias description:</strong>
    <%= evaluation.bias_description %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= evaluation.comments %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= evaluation.task_id %>
  </p>

</div>

app/views/evaluations/_form.html.erb
<%= form_with(model: evaluation, class: "form") do |form| %>
  <% if evaluation.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
        <% evaluation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :scenario_id, @task.scenario_id %>
  <%= hidden_field_tag :task_id, @task.id %>
  
  <div class="form-group">
    <%= form.label :accuracy, class: "control-label" %>
    <%= form.number_field :accuracy, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :accuracy_description, class: "control-label" %>
    <%= form.text_area :accuracy_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :relevance, class: "control-label" %>
    <%= form.number_field :relevance, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :relevance_description, class: "control-label" %>
    <%= form.text_area :relevance_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bias, class: "control-label" %>
    <%= form.number_field :bias, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bias_description, class: "control-label" %>
    <%= form.text_area :bias_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comments, class: "control-label" %>
    <%= form.text_area :comments, class: "form-control" %>
  </div>

  <br>

  <div class="form-group">
    <%= form.submit "Next", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h1>Editing evaluation</h1>

<%= render "form", evaluation: @evaluation %>

<br>

<div>
  <%= link_to "Show this evaluation", @evaluation %> |
  <%= link_to "Back to evaluations", evaluations_path %>
</div>

app/views/evaluations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evaluations</h1>

<div id="evaluations">
  <% @evaluations.each do |evaluation| %>
    <%= render evaluation %>
    <p>
      <%= link_to "Show this evaluation", evaluation %>
    </p>
  <% end %>
</div>

<%= link_to "New evaluation", new_evaluation_path %>

app/views/evaluations/new.html.erb
<h2><%= @scenario.name%></h2>
<p><strong>Task:</strong> <%= @task.name %></p>
<p><strong>Description:</strong> <%= @task.description %></p>

<%= render "form", evaluation: @evaluation %>

<br>

app/views/evaluations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluation %>

<div>
  <%= link_to "Edit this evaluation", edit_evaluation_path(@evaluation) %> |
  <%= link_to "Back to evaluations", evaluations_path %>

  <%= button_to "Destroy this evaluation", @evaluation, method: :delete %>
</div>