config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :evaluations
  resources :tasks
  resources :scenarios

  # Set evaluation sequence
  resources :scenarios do
    member do
      get 'start'
      get 'evaluations'
    end
    resources :tasks, only: %i[show] do
      member do
        get 'next'
      end
      resources :gpt_prompts, only: %i[create]
      resources :evaluations, only: %i[new create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "scenarios#index"
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :description, presence: true, length: { maximum: 1000 }
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: %i[ show edit update destroy start evaluations ]
  before_action :authenticate_user!
  before_action :check_lecturer, only: [:new, :create, :edit, :update, :destroy]

  # Start the evaluation process
  def start
    @task = @scenario.tasks.first
    if @task
      redirect_to new_scenario_task_evaluation_path(@scenario, @task)
    else
      redirect_to scenario_path(@scenario), notice: 'No tasks available for this scenario'
    end
  end

  # GET /scenarios or /scenarios.json
  def index
    @scenarios = Scenario.all
  end

  # GET /scenarios/1 or /scenarios/1.json
  def show
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios or /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to scenarios_url, notice: "Scenario was successfully created." }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1 or /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to scenario_url(@scenario), notice: "Scenario was successfully updated." }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1 or /scenarios/1.json
  def destroy
    @scenario.destroy!

    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: "Scenario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def evaluations
    # This line retrieves all tasks associated with a specific scenario, including their evaluations. It does so by:
    # 1. Preloading the evaluations for each task to optimize query performance and avoid N+1 query issues.
    # 2. Ordering the tasks by their ID in ascending order to ensure a consistent sequence.
    # 3. Mapping over each task to create a new array where each element is a two-element array:
    #    - The first element is the task itself.
    #    - The second element is an array of the task's evaluations, ordered by their creation date in ascending order.
    # The result is assigned to @evaluations_by_task, providing a structured representation of tasks and their evaluations.
    # @tasks = @scenario.tasks 
    @evaluations_by_task = @scenario.tasks.includes(:evaluations).order(:id).map { |task| [task, task.evaluations.order(:created_at)] }
    
    if @evaluations_by_task.empty?
      redirect_to scenarios_path, notice: 'No evaluations available for this scenario'
    end
  end

  private
    def check_lecturer
      unless current_user.lecturer?
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Not authorized" }
        format.json { head :no_content }
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scenario_params
      params.require(:scenario).permit(:name, :description)
    end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_with(model: scenario, class: "form") do |form| %>
  <% if scenario.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
        <% scenario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div class="form-group">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  </form>
<% end %>

app/views/scenarios/_scenario.html.erb
<div id="<%= dom_id scenario %>">
  <p>
    <strong>Name:</strong>
    <%= scenario.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= scenario.description %>
  </p>

</div>

app/views/scenarios/edit.html.erb
<h1>Editing scenario</h1>

<%= render "form", scenario: @scenario %>

<br>

<div>
  <%= link_to "Show this scenario", @scenario %> |
  <%= link_to "Back to scenarios", scenarios_path %>
</div>

app/views/scenarios/evaluations.html.erb
<!-- app/views/scenarios/evaluations.html.erb -->
<h1>Evaluations for <%= @scenario.name %></h1>

<% @evaluations_by_task.each do |task, evaluations| %>
  <div class="card mb-4">
    <div class="card-header">
      <h2>Task: <%= task.name %></h2>
    </div>
    <div class="card-body">
      <p><%= task.description %></p>
      <% if evaluations.any? %>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>Accuracy</th>
                <th>Accuracy Description</th>
                <th>Relevance</th>
                <th>Relevance Description</th>
                <th>Bias</th>
                <th>Bias Description</th>
                <th>Comments</th>
                <th>Submitted At</th>
                <th>Submitted By</th>
              </tr>
            </thead>
            <tbody>
              <% evaluations.each do |evaluation| %>
                <tr>
                  <td><%= evaluation.accuracy %></td>
                  <td class="text-wrap"><%= evaluation.accuracy_description %></td>
                  <td><%= evaluation.relevance %></td>
                  <td class="text-wrap"><%= evaluation.relevance_description %></td>
                  <td><%= evaluation.bias %></td>
                  <td class="text-wrap"><%= evaluation.bias_description %></td>
                  <td class="text-wrap"><%= evaluation.comments %></td>
                  <td><%= evaluation.created_at %></td>
                  <td><%= evaluation.user.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p>No evaluations for this task.</p>
      <% end %>
    </div>
  </div>
<% end %>

<%= link_to 'Back to Scenarios', scenarios_path, class: 'btn btn-primary' %>

app/views/scenarios/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="page-title">
  <h1>Scenarios</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= link_to scenario.name, scenario %></td>
        <% if current_user.lecturer? %>
          <td>
            <%= link_to "Edit", edit_scenario_path(scenario), class: "btn btn-primary" %>
            <%= link_to 'Evaluations', evaluations_scenario_path(scenario), class: 'btn btn-info' %>
          </td>
          <% else %>
          <td>
            <%= link_to 'Start Scenario', start_scenario_path(scenario), class: 'btn btn-primary' %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.lecturer? %>
  <%= link_to "New scenario", new_scenario_path, class: "btn btn-success" %>
<% end %>

app/views/scenarios/new.html.erb
<h1>New scenario</h1>

<%= render "form", scenario: @scenario %>

<br>

<div>
  <%= link_to "Back to scenarios", scenarios_path %>
</div>

app/views/scenarios/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h2><%=@scenario.name%></h2>
    </div>
    <div class="card-body">
      <%= @scenario.description %>
    </div>
    <div class="card-footer text-right">
      <% if current_user.lecturer? %>
        <%= link_to "Edit this scenario", edit_scenario_path(@scenario), class: "btn btn-primary mr-2" %>
      <% end %>
      <%= link_to "Back to scenarios", scenarios_path, class: "btn btn-secondary" %>
    </div>
    <% if current_user.lecturer? %>
      <div class="card-footer text-left">
        <%= link_to 'Evaluations', evaluations_scenario_path(@scenario), class: 'btn btn-info' %>
      </div>
      <div class="card-footer text-left">
        <%= button_to "Delete", @scenario, method: :delete, class: "btn btn-danger ml-2", data: { confirm: "Are you sure you want to delete this scenario?" } %>
      </div>
    <% end %>
  </div>

  <div class="mt-4">
    <%= link_to 'Start Scenario', start_scenario_path(@scenario), class: 'btn btn-primary' %>
  </div>
</div>