config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :evaluations
  resources :tasks
  resources :scenarios

  # Set evaluation sequence
  resources :scenarios do
    member do
      get 'start'
      get 'evaluations'
    end
    resources :tasks, only: %i[show] do
      member do
        get 'next'
      end
      resources :gpt_prompts, only: %i[create]
      resources :evaluations, only: %i[new create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "scenarios#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LlmWorkshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">ChatGPT Workshop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Scenarios', scenarios_path, class: 'nav-link' %>
              </li>
              <% if current_user.lecturer? %>
                <li class="nav-item">
                  <%= link_to 'Tasks', tasks_path, class: 'nav-link' %>
                </li>
              <% end %>
            <% end %>
          </ul>
          <div class="d-flex">
            <% if user_signed_in? %>
              <div class="d-flex align-items-center">
                <div class="nav-item">
                  <span class="navbar-text">
                    Welcome <%= current_user.email %>
                  </span>
                </div>
              </div>
              </div>
              <div class="nav-item ms-2">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
              </div>
            <% else %>
              <div class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-success" %>
              </div>
              <div class="nav-item ms-2">
                <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>